# Generated by Django 6.0.6 on 2026-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('account_sid', models.CharField(blank=True, default='', max_length=64)),
                ('auth_token', models.CharField(blank=True, default='', max_length=64)),
                ('from_number', models.CharField(blank=True, default='', max_length=20)),
                ('message_template', models.TextField(default='Thank you {donorName} for your donation! Al-Najaat Foundation has received your amount: PKR {amount}. JazakAllah Khair!')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Twilio settings',
            },
        ),
    ]
