# Generated by Django 6.0.6 on 2026-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_twiliosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliosettings',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
