# Generated by Django 6.0.6 on 2026-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_box_key_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliosettings',
            name='message_template',
            field=models.TextField(default='Thank you {name} for your donation! Al-Najaat Foundation has received your amount: PKR {amount}. JazakAllah Khair!'),
        ),
    ]
